part of directus_i18n;

/// Generator for creating I18nKeys enum from Directus content
class DirectusI18nKeyGenerator {
  /// Generate I18nKeys enum from Directus and write to file
  /// 
  /// [baseUrl] - Directus base URL
  /// [accessToken] - Directus access token
  /// [outputPath] - Output file path for generated enum
  /// [collectionName] - Directus collection name (default: 'app_contents')
  /// [enumName] - Name of the generated enum (default: 'I18nKeys')
  /// 
  /// Example:
  /// ```dart
  /// await DirectusI18nKeyGenerator.generate(
  ///   baseUrl: 'https://your-directus.com',
  ///   accessToken: 'your-token',
  ///   outputPath: 'lib/i18n_keys.dart',
  /// );
  /// ```
  static Future<void> generate({
    required String baseUrl,
    required String accessToken,
    required String outputPath,
    String collectionName = 'app_contents',
    String enumName = 'I18nKeys',
  }) async {
    final logger = Logger();

    try {
      // Create Dio client
      final dio = Dio(BaseOptions(baseUrl: baseUrl));

      // Fetch data from Directus
      logger.i('Fetching translations from $baseUrl...');
      final response = await dio.get(
        '/items/$collectionName',
        queryParameters: {
          'access_token': accessToken,
          'fields': 'id,translations.value,translations.draft_value',
          'filter[status][_in]': 'published,draft',
          'deep[translations][_filter][value][_nnull]': 'true',
          'limit': '-1',
        },
      );

      // Generate enum content
      final buffer = StringBuffer();
      buffer.writeln('/// GENERATED CODE - DO NOT MODIFY BY HAND');
      buffer.writeln('/// Generated by DirectusI18nKeyGenerator');
      buffer.writeln('/// Run this script again to update');
      buffer.writeln('///');
      buffer.writeln('/// To regenerate, run:');
      buffer.writeln('/// dart run directus_i18n:generate');
      buffer.writeln();
      buffer.writeln("import 'package:directus_i18n/directus_i18n.dart';");
      buffer.writeln();
      buffer.writeln('enum $enumName implements I18nKey {');
      buffer.writeln("  empty('0', defaultFallbackKey: ''),");

      // Convert response and generate enum cases
      final data = response.data['data'] as List;
      logger.i('Found ${data.length} translation keys');

      for (var item in data) {
        final id = item['id'];
        final translations = item['translations'] as List?;
        
        if (translations != null && translations.isNotEmpty) {
          final value = translations[0]['value'];
          if (value != null) {
            final sanitizedValue = _sanitizeString(value);
            buffer.writeln("  key$id('$id', defaultFallbackKey: '$sanitizedValue'),");
          }
        }
      }

      // Add enum boilerplate
      buffer.writeln('''
  ;

  const $enumName(this.key, {this.defaultFallbackKey});

  @override
  final String key;

  @override
  final String? defaultFallbackKey;

  /// Get enum by key ID
  static $enumName getEnum({required String forId}) {
    return $enumName.values.byName("key\$forId");
  }

  /// Try to get enum by key ID, returns null if not found
  static $enumName? tryGetEnum({required String forId, String prefix = "key"}) {
    try {
      return $enumName.values.byName("\$prefix\$forId");
    } catch (e) {
      return null;
    }
  }
}
''');

      // Write to file
      final outputFile = File(outputPath);
      await outputFile.writeAsString(buffer.toString());
      
      logger.i('✅ Successfully generated $enumName enum at $outputPath');
      logger.i('Total keys: ${data.length}');
    } catch (e, stackTrace) {
      logger.e('❌ Failed to generate I18n keys', error: e, stackTrace: stackTrace);
      rethrow;
    }
  }

  /// Sanitize string for Dart code generation
  static String _sanitizeString(String input) {
    return input
        .replaceAll('\n', '\\n')
        .replaceAll('\r', '\\r')
        .replaceAll('\t', '\\t')
        .replaceAll("'", "\\'")
        .replaceAll('\\"', '"')
        .replaceAll('\$', '\\\$');
  }
}

/// Standalone executable for generating keys
/// Can be run with: dart run directus_i18n:generate
class GeneratorCLI {
  static Future<void> run(List<String> args) async {
    // This would be implemented in bin/generate.dart
    print('Use DirectusI18nKeyGenerator.generate() in your own script');
  }
}

