part of directus_i18n;

/// Runtime Enum Generator that generates enum code and stores it in codebase
/// This allows adding new keys without releasing new app versions
class RuntimeEnumGenerator {
  static final Logger _logger = Logger();
  static const String _generatedDir = 'lib/generated';
  static const String _enumFileName = 'runtime_i18n_keys.dart';
  
  /// Generate enum at runtime and store in codebase
  static Future<void> generateAndStore({
    required String baseUrl,
    required String accessToken,
    String collectionName = 'app_contents',
    String enumName = 'RuntimeI18nKeys',
  }) async {
    try {
      _logger.i('🔄 Generating runtime enum from Directus...');
      
      // Create generated directory if it doesn't exist
      final generatedDir = Directory(_generatedDir);
      if (!await generatedDir.exists()) {
        await generatedDir.create(recursive: true);
      }
      
      // Fetch data from Directus
      final dio = Dio(BaseOptions(baseUrl: baseUrl));
      final response = await dio.get(
        '/items/$collectionName',
        queryParameters: {
          'access_token': accessToken,
          'fields': 'id,translations.value,translations.draft_value',
          'filter[status][_in]': 'published,draft',
          'deep[translations][_filter][value][_nnull]': 'true',
          'limit': '-1',
        },
      );
      
      // Generate enum content
      final buffer = StringBuffer();
      _generateEnumHeader(buffer, enumName);
      
      final data = response.data['data'] as List;
      _logger.i('Found ${data.length} translation keys');
      
      // Generate enum cases
      for (var item in data) {
        final id = item['id'];
        final translations = item['translations'] as List?;
        
        if (translations != null && translations.isNotEmpty) {
          final value = translations[0]['value'];
          if (value != null) {
            final sanitizedValue = _sanitizeString(value);
            buffer.writeln("  key$id('$id', defaultFallbackKey: '$sanitizedValue'),");
          }
        }
      }
      
      _generateEnumFooter(buffer, enumName);
      
      // Write to file
      final outputFile = File('$_generatedDir/$_enumFileName');
      await outputFile.writeAsString(buffer.toString());
      
      _logger.i('✅ Runtime enum generated at $_generatedDir/$_enumFileName');
      _logger.i('Total keys: ${data.length}');
      
    } catch (e, stackTrace) {
      _logger.e('❌ Failed to generate runtime enum', error: e, stackTrace: stackTrace);
      rethrow;
    }
  }
  
  /// Generate enum header
  static void _generateEnumHeader(StringBuffer buffer, String enumName) {
    buffer.writeln('/// GENERATED CODE - DO NOT MODIFY BY HAND');
    buffer.writeln('/// Generated by RuntimeEnumGenerator at ${DateTime.now().toIso8601String()}');
    buffer.writeln('/// This file is generated at runtime and stored in codebase');
    buffer.writeln('///');
    buffer.writeln('/// To regenerate, call:');
    buffer.writeln('/// RuntimeEnumGenerator.generateAndStore()');
    buffer.writeln();
    buffer.writeln("import 'package:directus_i18n/directus_i18n.dart';");
    buffer.writeln();
    buffer.writeln('enum $enumName implements I18nKey {');
    buffer.writeln("  empty('0', defaultFallbackKey: ''),");
  }
  
  /// Generate enum footer
  static void _generateEnumFooter(StringBuffer buffer, String enumName) {
    buffer.writeln('''
  ;

  const $enumName(this.key, {this.defaultFallbackKey});

  @override
  final String key;

  @override
  final String? defaultFallbackKey;

  /// Get enum by key ID
  static $enumName getEnum({required String forId}) {
    return $enumName.values.byName("key\$forId");
  }

  /// Try to get enum by key ID, returns null if not found
  static $enumName? tryGetEnum({required String forId, String prefix = "key"}) {
    try {
      return $enumName.values.byName("\$prefix\$forId");
    } catch (e) {
      return null;
    }
  }

  /// Check if key exists in current enum
  static bool hasKey(String key) {
    return $enumName.values.any((e) => e.key == key);
  }

  /// Get all available keys
  static List<String> getAllKeys() {
    return $enumName.values.map((e) => e.key).toList();
  }
}
''');
  }
  
  /// Sanitize string for Dart code generation
  static String _sanitizeString(String input) {
    return input
        .replaceAll('\n', '\\n')
        .replaceAll('\r', '\\r')
        .replaceAll('\t', '\\t')
        .replaceAll("'", "\\'")
        .replaceAll('\\"', '"')
        .replaceAll('\$', '\\\$');
  }
  
  /// Check if generated enum exists
  static bool hasGeneratedEnum() {
    return File('$_generatedDir/$_enumFileName').existsSync();
  }
  
  /// Get generated enum file path
  static String getGeneratedEnumPath() {
    return '$_generatedDir/$_enumFileName';
  }
  
  /// Delete generated enum file
  static Future<void> deleteGeneratedEnum() async {
    final file = File('$_generatedDir/$_enumFileName');
    if (await file.exists()) {
      await file.delete();
      _logger.i('Deleted generated enum file');
    }
  }
  
  /// Get enum file modification time
  static DateTime? getGeneratedEnumModificationTime() {
    final file = File('$_generatedDir/$_enumFileName');
    if (file.existsSync()) {
      return file.lastModifiedSync();
    }
    return null;
  }
}
