#!/usr/bin/env dart

import 'dart:io';
import 'package:dio/dio.dart';
import 'package:dotenv/dotenv.dart';

/// Script to automatically generate enum files in codebase
/// This can be run as part of build process or CI/CD pipeline
/// 
/// Usage:
/// 1. Set up .env file with your Directus credentials
/// 2. Run: dart run scripts/auto_generate_enum.dart
/// 3. Enum files will be generated in lib/generated/

void main() async {
  // Load the .env file
  var env = DotEnv(includePlatformEnvironment: true)..load();

  // Access the environment variables
  final baseUrl = env['DIRECTUS_BASE_URL'];
  final accessToken = env['DIRECTUS_ACCESS_TOKEN'];
  final collectionName = env['DIRECTUS_COLLECTION_NAME'] ?? 'app_contents';
  final enumName = env['I18N_ENUM_NAME'] ?? 'AutoI18nKeys';

  if (baseUrl == null || accessToken == null) {
    print(
      "\x1B[31mError: DIRECTUS_BASE_URL and DIRECTUS_ACCESS_TOKEN must be set in the .env file.\x1B[0m",
    );
    exit(1);
  }

  print("🔄 Auto-generating enum files in codebase...");
  print("Base URL: $baseUrl");
  print("Collection: $collectionName");
  print("Enum Name: $enumName");
  print("");

  try {
    // Create generated directory if it doesn't exist
    final generatedDir = Directory('lib/generated');
    if (!await generatedDir.exists()) {
      await generatedDir.create(recursive: true);
    }

    // Fetch data from Directus
    final dio = Dio(BaseOptions(baseUrl: baseUrl));
    final response = await dio.get(
      '/items/$collectionName',
      queryParameters: {
        'access_token': accessToken,
        'fields': 'id,translations.value,translations.draft_value',
        'filter[status][_in]': 'published,draft',
        'deep[translations][_filter][value][_nnull]': 'true',
        'limit': '-1',
      },
    );

    // Generate enum content
    final buffer = StringBuffer();
    _generateEnumHeader(buffer, enumName);
    
    final data = response.data['data'] as List;
    print("Found ${data.length} translation keys");

    // Generate enum cases
    for (var item in data) {
      final id = item['id'];
      final translations = item['translations'] as List?;
      
      if (translations != null && translations.isNotEmpty) {
        final value = translations[0]['value'];
        if (value != null) {
          final sanitizedValue = _sanitizeString(value);
          buffer.writeln("  key$id('$id', defaultFallbackKey: '$sanitizedValue'),");
        }
      }
    }
    
    _generateEnumFooter(buffer, enumName);

    // Write to file
    final outputFile = File('lib/generated/$enumName.dart');
    await outputFile.writeAsString(buffer.toString());
    
    print("✅ Successfully generated $enumName enum at lib/generated/$enumName.dart");
    print("Total keys: ${data.length}");
    print("");
    print("📁 Generated files:");
    print("  - lib/generated/$enumName.dart");
    print("");
    print("💡 This enum can now be used in your Flutter app without releasing new versions!");
    print("   The enum will be automatically updated when you run this script again.");

  } catch (e) {
    print("\x1B[31mFailed to generate enum: $e\x1B[0m");
    exit(1);
  }
}

/// Generate enum header
void _generateEnumHeader(StringBuffer buffer, String enumName) {
  buffer.writeln('/// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('/// Generated by auto_generate_enum.dart at ${DateTime.now().toIso8601String()}');
  buffer.writeln('/// This file is generated automatically and stored in codebase');
  buffer.writeln('///');
  buffer.writeln('/// To regenerate, run:');
  buffer.writeln('/// dart run scripts/auto_generate_enum.dart');
  buffer.writeln('///');
  buffer.writeln('/// This allows adding new i18n keys without releasing new app versions');
  buffer.writeln();
  buffer.writeln("import 'package:directus_i18n/directus_i18n.dart';");
  buffer.writeln();
  buffer.writeln('enum $enumName implements I18nKey {');
  buffer.writeln("  empty('0', defaultFallbackKey: ''),");
}

/// Generate enum footer
void _generateEnumFooter(StringBuffer buffer, String enumName) {
  buffer.writeln('''
  ;

  const $enumName(this.key, {this.defaultFallbackKey});

  @override
  final String key;

  @override
  final String? defaultFallbackKey;

  /// Get enum by key ID
  static $enumName getEnum({required String forId}) {
    return $enumName.values.byName("key\$forId");
  }

  /// Try to get enum by key ID, returns null if not found
  static $enumName? tryGetEnum({required String forId, String prefix = "key"}) {
    try {
      return $enumName.values.byName("\$prefix\$forId");
    } catch (e) {
      return null;
    }
  }

  /// Check if key exists in current enum
  static bool hasKey(String key) {
    return $enumName.values.any((e) => e.key == key);
  }

  /// Get all available keys
  static List<String> getAllKeys() {
    return $enumName.values.map((e) => e.key).toList();
  }

  /// Get enum by key value (reverse lookup)
  static $enumName? getByKeyValue(String keyValue) {
    try {
      return $enumName.values.firstWhere((e) => e.key == keyValue);
    } catch (e) {
      return null;
    }
  }
}
''');
}

/// Sanitize string for Dart code generation
String _sanitizeString(String input) {
  return input
      .replaceAll('\n', '\\n')
      .replaceAll('\r', '\\r')
      .replaceAll('\t', '\\t')
      .replaceAll("'", "\\'")
      .replaceAll('\\"', '"')
      .replaceAll('\$', '\\\$');
}
